Model user
LetsGitFunky/myFridge pull request #5
Opened 2023-07-03 21:41 UTC by montejododger

Updaed User Model

2023-07-03 21:46 UTC, LetsGitFunky requested changes

2023-07-03 21:46 UTC, LetsGitFunky commented on backend/models/User.js
> +            ref: 'Ingredients',
Ingedient*

2023-07-03 22:16 UTC, NickGentryBJJ approved these changes

2023-07-04 00:21 UTC, LetsGitFunky approved these changes

2023-07-04 00:21 UTC, merged